### PR TITLE
Update build_monolithic.yml

### PR DESCRIPTION
**Pull request by Gcenx**

### CODE REVIEW

**Comment by Gcenx** [comment]
Quickly thrown together commits via mobile to test CX22 building

**Comment by Gcenx** [comment]
@dasmy not planning to merge this so don’t worry, just wanted to check if the new source builds without issue (it should)

The MoltenVK workflow can lightly drop the MoltenVK patches now since it’s 1.1.10, not sure about DXVK since it’s version wasn’t bumped.

**Comment by Gcenx** [comment]
Welp build_local.sh run built without issue it seems, so the actions just need to be updated properly to account for the the new MoltenVK and possible change to DXVK (maybe to fix building?)

Some libraries were imported into wine directly so can be dropped for CX22 but would still be needed for patriot releases.

**Comment by Gcenx** [comment]
Ignore the above message the workflow build 21.2.0 not 22.0.0….

Let’s see if I can resolve this without resorting to more patches

**Comment by Gcenx** [comment]
For the moment this doesn’t make much sense so closing.

**Comment by dasmy** [comment]
Sorry for not commenting this long - seems to be tradition that I am on vacation while you are active @Gcenx 😊

I can have a look into this in September.

**Comment by Gcenx** [comment]
@dasmy don’t worry about it enjoy your vacation.

**Comment by Gcenx** [comment]
@dasmy after upgrading my M1 mini then cleanly installing brew with only required deps managed to build CX22 based sources.

However that’s where the good news ends, CX22 is unfortunately rather broken especially for older titles so I’m really not sure it’s worth building/promoting this version. I’d rather hold off until the next releases were they’ll have hopefully resolved these problems.

**Pull request closed without merging**
