### PR TITLE
cx 21.2.0

### PR DESCRIPTION
**Pull request by dasmy**

### CODE REVIEW

**Comment by Gcenx** [comment]
brews copy of mingw-w64 still had the dlltool bug that breaks parallel compiles so this may fail due to this.

**Comment by Gcenx** [comment]
@dasmy gonna need to rebase this branch against head and force push to get actions to _try_ to compile this

**Comment by Gcenx** [comment]
Actions are acting stupid _sigh_ cleaned up the actions spam.

The CX19/20 failures are due to the dlltool regression that broken parallel compiles.

**Comment by dasmy** [comment]
> @dasmy gonna need to rebase this branch against head and force push to get actions to _try_ to compile this

Somehow my git-foo left me yesterday, sorry for the mess :-D

**Comment by dasmy** [comment]
> The CX19/20 failures are due to the dlltool regression that broken parallel compiles.
If it's a dlltool regression, why does it consistently appear in 19.x and 20.x but not 21.x? - Is there any patching or so we can do in 19.x and 20.x to fix this?

**Comment by Gcenx** [comment]
This doesn’t just affect CX19/20 if you ran this locally you’d get the same problem in CX21.

As all three jobs are ran at once so the amount of paralyzation per job becomes lower causing CX19/20 to fail but CX21 seemingly passes.

Without using outside resources (I have a versioned formula to bypass this that’s used by wine-staging) is disabling parallelization or simply wait for the open PR to get merged into brew.

This bug didn’t affect macports as my PR bumping *-w64-mingw32-binutils wasn’t merged as I’d discovered the bug so converted it to draft and await the upstram fix that’s now in PRs for both brew and macports. But even if it had affected macports as each component is handled individually it’s simple to override as component.

**Comment by dasmy** [comment]
> This doesn’t just affect CX19/20 if you ran this locally you’d get the same problem in CX21.
> 
> As all three jobs are ran at once so the amount of paralyzation per job becomes lower causing CX19/20 to fail but CX21 seemingly passes.
> 
> Without using outside resources (I have a versioned formula to bypass this that’s used by wine-staging) is disabling parallelization or simply wait for the open PR to get merged into brew.
> 
> This bug didn’t affect macports as my PR bumping *-w64-mingw32-binutils wasn’t merged as I’d discovered the bug so converted it to draft and await the upstram fix that’s now in PRs for both brew and macports. But even if it had affected macports as each component is handled individually it’s simple to override as component.

Ok, understood. - So we apparently need to wait for https://github.com/Homebrew/homebrew-core/pull/97110

**Comment by Gcenx** [comment]
My view is we should just merge this.

As the issue is an upstream issue that will be resolved once the PR gets merged not sure it’s worth waiting.

**Review by GabLeRoux — APPROVED** [review]

**Comment by GabLeRoux** [comment]
For what it's worth, I just read the code and linked upstream issue's changes, didn't understand all of the implications, but I don't have any objection 👍

**Comment by Gcenx** [comment]
@GabLeRoux the TLDR is upstream binutils broke parallel compiling, we’re compiling in parallel by default equals broken actions/builds.

Can we workaround this yes, is it worth the effort no.

**Comment by Gcenx** [comment]
Brew merged the PR now it’s it’s now a none issue

**Pull request merged**
