### PR TITLE
WIP: let's see how 21.1.0 is going

### PR DESCRIPTION
**Pull request by dasmy**

### CODE REVIEW

**Comment by dasmy** [comment]
Hi @Gcenx ,
Apparently, 21.1.0 builds without changes compared to 21.0.0.

Would there be anything to be changed / Are there any relevant new features to be activated?

**Comment by Gcenx** [comment]
The one new feature we should care about would already be covered by gnutls deps, aka gmp is now used for some additional encryption that isn’t covered by gnutls.

**Comment by Gcenx** [comment]
@dasmy did you want to do anything else to this?

**Comment by dasmy** [comment]
> @dasmy did you want to do anything else to this?

@Gcenx, nothing to add - just wanted to disable building 21.0.0 as we only are only building one minor per major version.

Apart from that I went down the rabbit hole of testing this build with Quantum Odyssey (https://www.quarksinteractive.com) but failed due to

    0160:err:winediag:wined3d_spirv_shader_backend_init_vk Wine was built without libvkd3d-shader support.

This is clearly not a blocker as non-3D software seems to work pretty well, but a bit disappointing :-)

**Review by Gcenx — APPROVED** [review]
This builds and I don't really see any issues with anything since it's just a basic version bump.

**Pull request merged**
