### PR TITLE
run python scripts in moltenVK fetchDependencies explicitly with python3

### LINKED ISSUE #37: MoltenVK-CW: won’t build on Monterey due to python27 removal
This would need to be accounted for as well.

### PR DESCRIPTION
**Pull request by dasmy**
for Monterey support, fixes #37

### CODE REVIEW

**Comment by dasmy** [comment]
@Gcenx : seems to have worked on Monterey or did I forget anything?

**Comment by Gcenx** [comment]
I don't think so, we'll only really know if this resolved the problem after someone tried it on the latest macOS Monterey patch

**Comment by dasmy** [comment]
> I don't think so, we'll only really know if this resolved the problem after someone tried it on the latest macOS Monterey patch

At least it did not work without that patch on my local Monterey machine 🙃

Wat do you think, which macOS version might be the best choice for the build action? Until now it was fixed to 10.15

**Comment by Gcenx** [comment]
> At least it did not work without that patch on my local Monterey machine 🙃

If that’s the case that confirms it’s resolved.

> Wat do you think, which macOS version might be the best choice for the build action? Until now it was fixed to 10.15

The action should alway be the latest version of macOS possible as it’s common for users to upgrade quickly.

**Comment by Gcenx** [comment]
Actually let’s just have everything set to macOS-latest as the versioned ones get deprecated/removed we’ll need to update the actions.

**Comment by dasmy** [comment]
> deprecated

Agree. - Currently, macOS-latest still seems to point to Big Sur, but likely, they will switch to Monterey soon (is currently in public beta).

**Pull request merged**
