### PR TITLE
Trying to fix Issue 6

### PR DESCRIPTION
**Pull request by s4pph1r3-dev**
I don't know wtf happen, but it seems like clang crashed
Maybe increasing the used core can change that, idk
I try what I can tbh
It may not work, it is completely untested.

### CODE REVIEW

**Comment by GabLeRoux** [comment]
hey btw I think this was fixed in a fork here:
https://github.com/Gcenx/macos-crossover-cloud-build

I just never received a pr for it, but it's probably good to have a look at one of the forks, there was a few related discussions, see in #6 comments

**Comment by GabLeRoux** [comment]
This one is also quite advanced:  
https://github.com/dasmy/macos-crossover-cloud-build/

**Comment by Gcenx** [comment]
> This one is also quite advanced:
> https://github.com/dasmy/macos-crossover-cloud-build/

Almost everything was fixed there, I mostly just provided comments to correct things as needed so my “fork” can just be ignored completely.

**Comment by GabLeRoux** [comment]
Yup, I went ahead and created a pr for the one from @dasmy <3, added you both as contributors in the readme.

If you're interested in being maintainers with pushing rights to the upstream repo (@Gcenx and @dasmy) let me know here and I'll go ahead, you're the best! 🤘

**Comment by Gcenx** [comment]
I guess it wouldn’t hurt, for the moment there’s not much reason to commit anything after the PR you opened is merged until CX21.

Also could close #9

**Comment by GabLeRoux** [comment]
Closing as I just merged #13, but feel free to suggest edits again and thanks for actually sending a contribution as this motivated me to look at the forks and actually update this project :tada:

**Pull request closed without merging**
